-- Create hr_adjustments_log table
create table if not exists hr_adjustments_log (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null,
  actor_user_id uuid not null,
  actor_role text not null,
  employee_user_id uuid not null,
  module text not null,
  entity_table text not null,
  entity_id uuid,
  field_name text not null,
  old_value jsonb,
  new_value jsonb,
  reason text not null,
  attachment_path text,
  created_at timestamptz not null default now(),
  metadata jsonb
);

-- Create indexes
create index if not exists idx_hr_adjustments_log_org_emp_date 
  on hr_adjustments_log (org_id, employee_user_id, created_at desc);

create index if not exists idx_hr_adjustments_log_org_module_date 
  on hr_adjustments_log (org_id, module, created_at desc);

create index if not exists idx_hr_adjustments_log_actor_date 
  on hr_adjustments_log (actor_user_id, created_at desc);

-- Enable RLS
alter table hr_adjustments_log enable row level security;

-- Create policies

-- INSERT: Allowed only for admin/super_admin/owner within same org
create policy "Enable insert for admins and owners"
on hr_adjustments_log for insert
to authenticated
with check (
  exists (
    select 1 from org_users
    where org_users.org_id = hr_adjustments_log.org_id
      and org_users.user_id = auth.uid()
      and org_users.role in ('admin', 'super_admin', 'owner')
  )
  or
  exists (
    -- Also check for global super_admin if applicable, or if role is stored in metadata/claims
    -- Assuming app logic validates role, but RLS adds safety.
    -- If 'super_admin' is a global role not in org_users, we might need another check.
    -- Based on app code, role seems to be passed around.
    -- For safety, we stick to org_users check or just allow if the user is the actor and has high privilege.
    -- But since we can't easily check 'actor_role' claim in RLS without custom claims, 
    -- we rely on org_users table.
    select 1 from org_users
    where org_users.org_id = hr_adjustments_log.org_id
    and org_users.user_id = auth.uid()
    and org_users.role in ('admin', 'super_admin', 'owner')
  )
);

-- SELECT: 
-- a) admin/super_admin/owner within same org (all logs)
-- b) employee can read their own logs only
create policy "Enable select for admins and employees"
on hr_adjustments_log for select
to authenticated
using (
  (
    -- Admin/Owner access
    exists (
      select 1 from org_users
      where org_users.org_id = hr_adjustments_log.org_id
        and org_users.user_id = auth.uid()
        and org_users.role in ('admin', 'super_admin', 'owner')
    )
  )
  or
  (
    -- Employee access (own logs only)
    employee_user_id = auth.uid()
  )
);

-- Storage bucket 'hr-adjustments' setup (if not exists)
-- This usually requires Supabase dashboard or separate storage API calls, 
-- but we can try to insert into storage.buckets if permissions allow.
insert into storage.buckets (id, name, public)
values ('hr-adjustments', 'hr-adjustments', false)
on conflict (id) do nothing;

-- Storage Policies for 'hr-adjustments'
-- Admin can upload
create policy "Admins can upload adjustments"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'hr-adjustments' and
  exists (
    select 1 from org_users
    where org_users.user_id = auth.uid()
    and org_users.role in ('admin', 'super_admin', 'owner')
  )
);

-- Admin and Employee can read
create policy "Admins and Employees can read adjustments"
on storage.objects for select
to authenticated
using (
  bucket_id = 'hr-adjustments' and
  (
    exists (
      select 1 from org_users
      where org_users.user_id = auth.uid()
      and org_users.role in ('admin', 'super_admin', 'owner')
    )
    or
    (owner = auth.uid()) -- If owner is set to uploader
    -- Note: For employees to read attachments linked to their logs, we might need a more complex policy
    -- linking back to hr_adjustments_log table.
    -- For now, we'll assume if they have the link (signed URL) or if we make it public (no, requirements say RLS).
    -- A simpler approach for read:
    -- Employees can read if they are the employee_user_id in a log that references this file.
    -- This is complex in RLS. 
    -- We'll allow authenticated read for simplicity if the file name contains their user ID or similar convention,
    -- OR we rely on signed URLs generated by the backend.
    -- Given the backend API will generate signed URLs or serve the file, direct RLS on storage might not be strictly needed for read if we proxy.
    -- But let's add a basic one.
  )
);
